name: Daily Zip Downloader

permissions:
  contents: write

on:
  workflow_dispatch:  # Allows manual triggering.
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC.
    - cron: "0 12 * * *"  # Runs daily at 12pm (noon) UTC.

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install downloader dependencies
        working-directory: downloader
        run: pip install -r requirements.txt

      - name: Run download script
        working-directory: downloader
        run: python cn-history-data-downloader.py

      - name: Move downloaded files to repository root
        run: |
          # Check if the folder exists in the downloader folder.
          if [ -d downloader/downloaded_zips ]; then
              # Move it to the repository root.
              mv downloader/downloaded_zips ./downloaded_zips
              echo "Moved downloaded_zips folder to repository root."
          else
              echo "No downloaded_zips folder found in downloader."
          fi

      - name: Prepare downloaded_zips folder
        run: mkdir -p downloaded_zips

      - name: Commit new downloads
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          if [ -d downloaded_zips ] && [ "$(ls -A downloaded_zips)" ]; then
            git add downloaded_zips/
            # Only commit if there are changes.
            git diff --cached --exit-code || git commit -m "Add daily downloaded zip files"
          else
            echo "downloaded_zips folder is empty or does not exist; nothing to commit."
          fi
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push || echo "No new commit to push"
